import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React from 'react';
import Card from '../components/Card';

function Home({initialProps}) {

  const [prompt, setPrompt] = React.useState();

  const updatePrompt = e => setPrompt(e.target.value);

  function handleSubmit(e) {
    e.preventDefault();
    // console.log(prompt);

    // const data = {
    //   prompt: prompt,
    //   temperature: 0.5,
    //   max_tokens: 64,
    //   top_p: 1.0,
    //   frequency_penalty: 0.0,
    //   presence_penalty: 0.0,
    // };

    // const response = fetch("https://api.openai.com/v1/engines/text-curie-001/completions", {
    //   method: "POST",
    //   headers: {
    //     "Content-Type": "application/json",
    //     Authorization: `Bearer ${process.env.OPENAI_SECRET}`,
    //   },
    //   body: JSON.stringify(data),
    // });

    // response.then(res => res.json())
    // .then(json => {
    //   console.log(json);
    // }
    // ).catch(err => {
    //   console.log(err);
    // }
    // );
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Fun with GPT-3
        </h1>

        <form className={styles.form} onSubmit={handleSubmit}>
          <h3 type="prompt_text">Enter prompt</h3>
          <textarea 
              contentEditable={true}
              onChange={updatePrompt}
              value={prompt}
              suppressContentEditableWarning={true}
              placeholder="Enter your prompt..." 
              type="text" id="prompt" name="prompt" 
              size="50" required />
          <button type="submit">Submit</button>
        </form>

        <div className="cards" id="cards">
            {initialProps.map((card) => (
                <Card key={card[0]} prompt={card[1]} answer={card[2]} />
            ))}
        </div>
      </main>
    </div>
  )
}

export async function getStaticProps() {
  const initialProps = [];
  const prompts = ['What is the capital of the United States?',
              'What is the meaning of life?',
              'How to calculate the area of a circle?'];

  for (let i = 0; i < 3; i++) {
    const data = {
      prompt: prompts[i],
      temperature: 0.5,
      max_tokens: 64,
      top_p: 1.0,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
    };

    const response = await fetch("https://api.openai.com/v1/engines/text-curie-001/completions", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${process.env.OPENAI_SECRET}`,
      },
      body: JSON.stringify(data),
    });

    const res = await response.json();
    initialProps.push([res.id, data.prompt, res.choices[0].text]);
  }

  return {props: {initialProps}}
}

export default Home;